// A Calculator Project
// Note that almost all the code on this page code be generated by an IDE.
// The "application developer" is more interested in deciding what "controls"
// need to exist on the client, and how to respond to user interactions with
// these controls.

// This function could be generated by an IDE
function Form1(parent)
{
  // extends Window
  //this.base = Window;
	this.base = Form;
  this.base();
  
  // private members
  var me = this;
  var result;
  var button0;
  var button1;
  var button2;
  var button3;
  var button4;
  var button5;
  var button6;
  var button7;
  var button8;
  var button9;
  var buttonClr;
  var buttonEql;
  var buttonPls;
  var buttonMns;
  var buttonMlt;
  var buttonDvd;
  var buttonClose;
  
  var init = function()
  {
    // initialize controls 
    result = new TextBox();
    button0 = new Button();
    button1 = new Button();
    button2 = new Button();
    button3 = new Button();
    button4 = new Button();
    button5 = new Button();
    button6 = new Button();
    button7 = new Button();
    button8 = new Button();
    button9 = new Button();
    buttonClr = new Button();
    buttonEql = new Button();
    buttonPls = new Button();
    buttonMns = new Button();
    buttonMlt = new Button();
    buttonDvd = new Button();
    buttonClose = new Button();
    
    // result
    result.Name = 'result';
    result.Text = '0';
    result.Length = 16;
    result.Location(50, 50); 
    
    // button0
    button0.Name = 'button0';
    button0.Text = ' 0 ';
    button0.Location(50, 150);
    
    // button1
    button1.Name = 'button1';
    button1.Text = ' 1 ';
    button1.Location(50, 125);

    // button2
    button2.Name = 'button2';
    button2.Text = ' 2 ';
    button2.Location(80, 125);

    // button3
    button3.Name = 'button3';
    button3.Text = ' 3 ';
    button3.Location(110, 125);

    // button4
    button4.Name = 'button4';
    button4.Text = ' 4 ';
    button4.Location(50, 100);

    // button5
    button5.Name = 'button5';
    button5.Text = ' 5 ';
    button5.Location(80, 100);

    // button6
    button6.Name = 'button6';
    button6.Text = ' 6 ';
    button6.Location(110, 100);
    
    // button7
    button7.Name = 'button7';
    button7.Text = ' 7 ';
    button7.Location(50, 75);

    // button8
    button8.Name = 'button8';
    button8.Text = ' 8 ';
    button8.Location(80, 75);

    // button9
    button9.Name = 'button9';
    button9.Text = ' 9 ';
    button9.Location(110, 75);

    // buttonClr
    buttonClr.Name = 'buttonClr';
    buttonClr.Text = ' C ';
    buttonClr.Location(80, 150);

    // buttonEql
    buttonEql.Name = 'buttonEql';
    buttonEql.Text = ' = ';
    buttonEql.Location(110, 150);

    // buttonPls
    buttonPls.Name = 'buttonPls';
    buttonPls.Text = ' + ';
    buttonPls.Location(140, 150);

    // buttonMns
    buttonMns.Name = 'buttonMns';
    buttonMns.Text = ' - ';
    buttonMns.Location(140, 125);

    // buttonMlt
    buttonMlt.Name = 'buttonMlt';
    buttonMlt.Text = ' * ';
    buttonMlt.Location(140, 100);

    // buttonDvd
    buttonDvd.Name = 'buttonDvd';
    buttonDvd.Text = ' / ';
    buttonDvd.Location(140, 75);

    // buttonClose
    buttonClose.Name = 'buttonClose';
    buttonClose.Text = 'Close Calculator';
    buttonClose.Location(50, 190);

    // WindowPage1
    me.Parent = parent;
    me.Title = 'Calculator'
    me.Name = 'WindowPage1'
    me.Location(100, 100);
    me.Size(220, 250);
    me.AddControl(result);
    me.AddControl(button0);
    me.AddControl(button1);
    me.AddControl(button2);
    me.AddControl(button3);
    me.AddControl(button4);
    me.AddControl(button5);
    me.AddControl(button6);
    me.AddControl(button7);
    me.AddControl(button8);
    me.AddControl(button9);
    me.AddControl(buttonClr);
    me.AddControl(buttonEql);
    me.AddControl(buttonPls);
    me.AddControl(buttonMns);
    me.AddControl(buttonMlt);
    me.AddControl(buttonDvd);
    me.AddControl(buttonClose);    
    
    // render window
		me.Container = parent.Container;	//addition
    me.Show();
    
    // add event handlers
    button0.Click(button_click);
    button1.Click(button_click);
    button2.Click(button_click);
    button3.Click(button_click);
    button4.Click(button_click);
    button5.Click(button_click);
    button6.Click(button_click);
    button7.Click(button_click);
    button8.Click(button_click);
    button9.Click(button_click);
    buttonClr.Click(button_click); 
    buttonEql.Click(button_click); 
    buttonPls.Click(button_click); 
    buttonMns.Click(button_click); 
    buttonMlt.Click(button_click); 
    buttonDvd.Click(button_click);  
    buttonClose.Click(buttonClose_click);
  }

  //! DEVELOPER DEFINED CODE STARTS HERE !
  var val1;
  var val2;
  var op = ''; 

  var buttonClose_click = function(event)
  {
    me.Hide();
  }
  
  var button_click = function(event)
  {
    var pressed = event.target.getAttribute("id");
    var btn = pressed.substring(6,pressed.length);
    
    //alert(btn);
    switch(btn)
    {
      case 'Clr': 
        {
          result.Text = '0';
          break;
        }
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        {
          if (result.Text == 0 || (op != '' && result.Text == val1))
          {
            result.Text = btn;
          }
          else
          {
            result.Text = result.Text + btn;
          }
          break;
        }
      case 'Pls': 
      case 'Mns': 
      case 'Mlt': 
      case 'Dvd': 
        {
          val1 = result.Text * 1;
          op = btn;
          break;
        }           
      case 'Eql': 
        {
          val2 = result.Text * 1;
          if(op == 'Pls') {result.Text = val1 + val2;}
          if(op == 'Mns') {result.Text = val1 - val2;}
          if(op == 'Mlt') {result.Text = val1 * val2;}
          if(op == 'Dvd') {result.Text = val1 / val2;}
          op = '';
          break;
        }       
    }
  }
  //! DEVELOPER DEFINED CODE ENDS HERE !
  
  // initialize
  init();
}
