// A Test Project
// Note that almost all the code on this page code be generated by an IDE.
// The "application developer" is more interested in deciding what "controls"
// need to exist on the client, and how to respond to user interactions with
// these controls.

// This function could be generated by an IDE
function Page1(parent)
{
  // extends page
  this.base = Page;
  this.base();
  
  // private members
  var me = this;
  var cmd1;
  var cmd2;
  
  var init = function()
  {
    // initialize controls
    cmd1 = new Button();
    cmd2 = new Button();
    
    // cmd1
    cmd1.Name = 'cmd1';
    cmd1.Text = 'Start Calc 1';
    cmd1.Location(100, 150);    

    // cmd2
    cmd2.Name = 'cmd2';
    cmd2.Text = 'Start Calc 2';
    cmd2.Location(100, 200);    

    me.Parent = parent;
    me.Container = parent.document;
    me.Title = 'Example Application'
    me.AddControl(cmd1);
    me.AddControl(cmd2);
        
    // show form stuff
    me.Show();

    // add event handlers
    cmd1.Click(cmd1_click);
    cmd2.Click(cmd2_click);
  }

  //! DEVELOPER DEFINED CODE STARTS HERE !
  var cmd1_click = function(event)
  {
    var x = 6;
		var y = ++x
		alert("x:" + x);
		alert("y:" + y);
  }
  
  var cmd2_click = function(event)
  {
		var myForm1 = new Form1(me);
  }
  //! DEVELOPER DEFINED CODE ENDS HERE !
  
  // initialize
  init();
}